// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: svg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_svg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_svg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_svg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_svg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_svg_2eproto;
namespace transport_catalogue_serialize {
class Color;
struct ColorDefaultTypeInternal;
extern ColorDefaultTypeInternal _Color_default_instance_;
class Point;
struct PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class Rgb;
struct RgbDefaultTypeInternal;
extern RgbDefaultTypeInternal _Rgb_default_instance_;
class Rgba;
struct RgbaDefaultTypeInternal;
extern RgbaDefaultTypeInternal _Rgba_default_instance_;
}  // namespace transport_catalogue_serialize
PROTOBUF_NAMESPACE_OPEN
template<> ::transport_catalogue_serialize::Color* Arena::CreateMaybeMessage<::transport_catalogue_serialize::Color>(Arena*);
template<> ::transport_catalogue_serialize::Point* Arena::CreateMaybeMessage<::transport_catalogue_serialize::Point>(Arena*);
template<> ::transport_catalogue_serialize::Rgb* Arena::CreateMaybeMessage<::transport_catalogue_serialize::Rgb>(Arena*);
template<> ::transport_catalogue_serialize::Rgba* Arena::CreateMaybeMessage<::transport_catalogue_serialize::Rgba>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace transport_catalogue_serialize {

// ===================================================================

class Point final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_serialize.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() override;
  explicit PROTOBUF_CONSTEXPR Point(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point& from) {
    Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_serialize.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalogue_serialize.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class Rgb final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_serialize.Rgb) */ {
 public:
  inline Rgb() : Rgb(nullptr) {}
  ~Rgb() override;
  explicit PROTOBUF_CONSTEXPR Rgb(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Rgb(const Rgb& from);
  Rgb(Rgb&& from) noexcept
    : Rgb() {
    *this = ::std::move(from);
  }

  inline Rgb& operator=(const Rgb& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rgb& operator=(Rgb&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Rgb& default_instance() {
    return *internal_default_instance();
  }
  static inline const Rgb* internal_default_instance() {
    return reinterpret_cast<const Rgb*>(
               &_Rgb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Rgb& a, Rgb& b) {
    a.Swap(&b);
  }
  inline void Swap(Rgb* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Rgb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Rgb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Rgb>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Rgb& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Rgb& from) {
    Rgb::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rgb* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_serialize.Rgb";
  }
  protected:
  explicit Rgb(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRedFieldNumber = 1,
    kGreenFieldNumber = 2,
    kBlueFieldNumber = 3,
  };
  // uint32 red = 1;
  void clear_red();
  uint32_t red() const;
  void set_red(uint32_t value);
  private:
  uint32_t _internal_red() const;
  void _internal_set_red(uint32_t value);
  public:

  // uint32 green = 2;
  void clear_green();
  uint32_t green() const;
  void set_green(uint32_t value);
  private:
  uint32_t _internal_green() const;
  void _internal_set_green(uint32_t value);
  public:

  // uint32 blue = 3;
  void clear_blue();
  uint32_t blue() const;
  void set_blue(uint32_t value);
  private:
  uint32_t _internal_blue() const;
  void _internal_set_blue(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalogue_serialize.Rgb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t red_;
    uint32_t green_;
    uint32_t blue_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class Rgba final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_serialize.Rgba) */ {
 public:
  inline Rgba() : Rgba(nullptr) {}
  ~Rgba() override;
  explicit PROTOBUF_CONSTEXPR Rgba(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Rgba(const Rgba& from);
  Rgba(Rgba&& from) noexcept
    : Rgba() {
    *this = ::std::move(from);
  }

  inline Rgba& operator=(const Rgba& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rgba& operator=(Rgba&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Rgba& default_instance() {
    return *internal_default_instance();
  }
  static inline const Rgba* internal_default_instance() {
    return reinterpret_cast<const Rgba*>(
               &_Rgba_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Rgba& a, Rgba& b) {
    a.Swap(&b);
  }
  inline void Swap(Rgba* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Rgba* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Rgba* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Rgba>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Rgba& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Rgba& from) {
    Rgba::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rgba* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_serialize.Rgba";
  }
  protected:
  explicit Rgba(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRgbFieldNumber = 1,
    kOpacityFieldNumber = 2,
  };
  // .transport_catalogue_serialize.Rgb rgb = 1;
  bool has_rgb() const;
  private:
  bool _internal_has_rgb() const;
  public:
  void clear_rgb();
  const ::transport_catalogue_serialize::Rgb& rgb() const;
  PROTOBUF_NODISCARD ::transport_catalogue_serialize::Rgb* release_rgb();
  ::transport_catalogue_serialize::Rgb* mutable_rgb();
  void set_allocated_rgb(::transport_catalogue_serialize::Rgb* rgb);
  private:
  const ::transport_catalogue_serialize::Rgb& _internal_rgb() const;
  ::transport_catalogue_serialize::Rgb* _internal_mutable_rgb();
  public:
  void unsafe_arena_set_allocated_rgb(
      ::transport_catalogue_serialize::Rgb* rgb);
  ::transport_catalogue_serialize::Rgb* unsafe_arena_release_rgb();

  // double opacity = 2;
  void clear_opacity();
  double opacity() const;
  void set_opacity(double value);
  private:
  double _internal_opacity() const;
  void _internal_set_opacity(double value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalogue_serialize.Rgba)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::transport_catalogue_serialize::Rgb* rgb_;
    double opacity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class Color final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_serialize.Color) */ {
 public:
  inline Color() : Color(nullptr) {}
  ~Color() override;
  explicit PROTOBUF_CONSTEXPR Color(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Color(const Color& from);
  Color(Color&& from) noexcept
    : Color() {
    *this = ::std::move(from);
  }

  inline Color& operator=(const Color& from) {
    CopyFrom(from);
    return *this;
  }
  inline Color& operator=(Color&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Color& default_instance() {
    return *internal_default_instance();
  }
  enum ColorVariantCase {
    kRgb = 1,
    kRgba = 2,
    kColorStr = 3,
    COLOR_VARIANT_NOT_SET = 0,
  };

  static inline const Color* internal_default_instance() {
    return reinterpret_cast<const Color*>(
               &_Color_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Color& a, Color& b) {
    a.Swap(&b);
  }
  inline void Swap(Color* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Color* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Color* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Color>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Color& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Color& from) {
    Color::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Color* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_serialize.Color";
  }
  protected:
  explicit Color(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRgbFieldNumber = 1,
    kRgbaFieldNumber = 2,
    kColorStrFieldNumber = 3,
  };
  // .transport_catalogue_serialize.Rgb rgb = 1;
  bool has_rgb() const;
  private:
  bool _internal_has_rgb() const;
  public:
  void clear_rgb();
  const ::transport_catalogue_serialize::Rgb& rgb() const;
  PROTOBUF_NODISCARD ::transport_catalogue_serialize::Rgb* release_rgb();
  ::transport_catalogue_serialize::Rgb* mutable_rgb();
  void set_allocated_rgb(::transport_catalogue_serialize::Rgb* rgb);
  private:
  const ::transport_catalogue_serialize::Rgb& _internal_rgb() const;
  ::transport_catalogue_serialize::Rgb* _internal_mutable_rgb();
  public:
  void unsafe_arena_set_allocated_rgb(
      ::transport_catalogue_serialize::Rgb* rgb);
  ::transport_catalogue_serialize::Rgb* unsafe_arena_release_rgb();

  // .transport_catalogue_serialize.Rgba rgba = 2;
  bool has_rgba() const;
  private:
  bool _internal_has_rgba() const;
  public:
  void clear_rgba();
  const ::transport_catalogue_serialize::Rgba& rgba() const;
  PROTOBUF_NODISCARD ::transport_catalogue_serialize::Rgba* release_rgba();
  ::transport_catalogue_serialize::Rgba* mutable_rgba();
  void set_allocated_rgba(::transport_catalogue_serialize::Rgba* rgba);
  private:
  const ::transport_catalogue_serialize::Rgba& _internal_rgba() const;
  ::transport_catalogue_serialize::Rgba* _internal_mutable_rgba();
  public:
  void unsafe_arena_set_allocated_rgba(
      ::transport_catalogue_serialize::Rgba* rgba);
  ::transport_catalogue_serialize::Rgba* unsafe_arena_release_rgba();

  // string color_str = 3;
  bool has_color_str() const;
  private:
  bool _internal_has_color_str() const;
  public:
  void clear_color_str();
  const std::string& color_str() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_color_str(ArgT0&& arg0, ArgT... args);
  std::string* mutable_color_str();
  PROTOBUF_NODISCARD std::string* release_color_str();
  void set_allocated_color_str(std::string* color_str);
  private:
  const std::string& _internal_color_str() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_color_str(const std::string& value);
  std::string* _internal_mutable_color_str();
  public:

  void clear_color_variant();
  ColorVariantCase color_variant_case() const;
  // @@protoc_insertion_point(class_scope:transport_catalogue_serialize.Color)
 private:
  class _Internal;
  void set_has_rgb();
  void set_has_rgba();
  void set_has_color_str();

  inline bool has_color_variant() const;
  inline void clear_has_color_variant();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ColorVariantUnion {
      constexpr ColorVariantUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::transport_catalogue_serialize::Rgb* rgb_;
      ::transport_catalogue_serialize::Rgba* rgba_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr color_str_;
    } color_variant_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// double x = 1;
inline void Point::clear_x() {
  _impl_.x_ = 0;
}
inline double Point::_internal_x() const {
  return _impl_.x_;
}
inline double Point::x() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Point::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.Point.x)
}

// double y = 2;
inline void Point::clear_y() {
  _impl_.y_ = 0;
}
inline double Point::_internal_y() const {
  return _impl_.y_;
}
inline double Point::y() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Point::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.Point.y)
}

// -------------------------------------------------------------------

// Rgb

// uint32 red = 1;
inline void Rgb::clear_red() {
  _impl_.red_ = 0u;
}
inline uint32_t Rgb::_internal_red() const {
  return _impl_.red_;
}
inline uint32_t Rgb::red() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Rgb.red)
  return _internal_red();
}
inline void Rgb::_internal_set_red(uint32_t value) {
  
  _impl_.red_ = value;
}
inline void Rgb::set_red(uint32_t value) {
  _internal_set_red(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.Rgb.red)
}

// uint32 green = 2;
inline void Rgb::clear_green() {
  _impl_.green_ = 0u;
}
inline uint32_t Rgb::_internal_green() const {
  return _impl_.green_;
}
inline uint32_t Rgb::green() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Rgb.green)
  return _internal_green();
}
inline void Rgb::_internal_set_green(uint32_t value) {
  
  _impl_.green_ = value;
}
inline void Rgb::set_green(uint32_t value) {
  _internal_set_green(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.Rgb.green)
}

// uint32 blue = 3;
inline void Rgb::clear_blue() {
  _impl_.blue_ = 0u;
}
inline uint32_t Rgb::_internal_blue() const {
  return _impl_.blue_;
}
inline uint32_t Rgb::blue() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Rgb.blue)
  return _internal_blue();
}
inline void Rgb::_internal_set_blue(uint32_t value) {
  
  _impl_.blue_ = value;
}
inline void Rgb::set_blue(uint32_t value) {
  _internal_set_blue(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.Rgb.blue)
}

// -------------------------------------------------------------------

// Rgba

// .transport_catalogue_serialize.Rgb rgb = 1;
inline bool Rgba::_internal_has_rgb() const {
  return this != internal_default_instance() && _impl_.rgb_ != nullptr;
}
inline bool Rgba::has_rgb() const {
  return _internal_has_rgb();
}
inline void Rgba::clear_rgb() {
  if (GetArenaForAllocation() == nullptr && _impl_.rgb_ != nullptr) {
    delete _impl_.rgb_;
  }
  _impl_.rgb_ = nullptr;
}
inline const ::transport_catalogue_serialize::Rgb& Rgba::_internal_rgb() const {
  const ::transport_catalogue_serialize::Rgb* p = _impl_.rgb_;
  return p != nullptr ? *p : reinterpret_cast<const ::transport_catalogue_serialize::Rgb&>(
      ::transport_catalogue_serialize::_Rgb_default_instance_);
}
inline const ::transport_catalogue_serialize::Rgb& Rgba::rgb() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Rgba.rgb)
  return _internal_rgb();
}
inline void Rgba::unsafe_arena_set_allocated_rgb(
    ::transport_catalogue_serialize::Rgb* rgb) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rgb_);
  }
  _impl_.rgb_ = rgb;
  if (rgb) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_serialize.Rgba.rgb)
}
inline ::transport_catalogue_serialize::Rgb* Rgba::release_rgb() {
  
  ::transport_catalogue_serialize::Rgb* temp = _impl_.rgb_;
  _impl_.rgb_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::transport_catalogue_serialize::Rgb* Rgba::unsafe_arena_release_rgb() {
  // @@protoc_insertion_point(field_release:transport_catalogue_serialize.Rgba.rgb)
  
  ::transport_catalogue_serialize::Rgb* temp = _impl_.rgb_;
  _impl_.rgb_ = nullptr;
  return temp;
}
inline ::transport_catalogue_serialize::Rgb* Rgba::_internal_mutable_rgb() {
  
  if (_impl_.rgb_ == nullptr) {
    auto* p = CreateMaybeMessage<::transport_catalogue_serialize::Rgb>(GetArenaForAllocation());
    _impl_.rgb_ = p;
  }
  return _impl_.rgb_;
}
inline ::transport_catalogue_serialize::Rgb* Rgba::mutable_rgb() {
  ::transport_catalogue_serialize::Rgb* _msg = _internal_mutable_rgb();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_serialize.Rgba.rgb)
  return _msg;
}
inline void Rgba::set_allocated_rgb(::transport_catalogue_serialize::Rgb* rgb) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.rgb_;
  }
  if (rgb) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(rgb);
    if (message_arena != submessage_arena) {
      rgb = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rgb, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rgb_ = rgb;
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_serialize.Rgba.rgb)
}

// double opacity = 2;
inline void Rgba::clear_opacity() {
  _impl_.opacity_ = 0;
}
inline double Rgba::_internal_opacity() const {
  return _impl_.opacity_;
}
inline double Rgba::opacity() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Rgba.opacity)
  return _internal_opacity();
}
inline void Rgba::_internal_set_opacity(double value) {
  
  _impl_.opacity_ = value;
}
inline void Rgba::set_opacity(double value) {
  _internal_set_opacity(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.Rgba.opacity)
}

// -------------------------------------------------------------------

// Color

// .transport_catalogue_serialize.Rgb rgb = 1;
inline bool Color::_internal_has_rgb() const {
  return color_variant_case() == kRgb;
}
inline bool Color::has_rgb() const {
  return _internal_has_rgb();
}
inline void Color::set_has_rgb() {
  _impl_._oneof_case_[0] = kRgb;
}
inline void Color::clear_rgb() {
  if (_internal_has_rgb()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.color_variant_.rgb_;
    }
    clear_has_color_variant();
  }
}
inline ::transport_catalogue_serialize::Rgb* Color::release_rgb() {
  // @@protoc_insertion_point(field_release:transport_catalogue_serialize.Color.rgb)
  if (_internal_has_rgb()) {
    clear_has_color_variant();
    ::transport_catalogue_serialize::Rgb* temp = _impl_.color_variant_.rgb_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.color_variant_.rgb_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::transport_catalogue_serialize::Rgb& Color::_internal_rgb() const {
  return _internal_has_rgb()
      ? *_impl_.color_variant_.rgb_
      : reinterpret_cast< ::transport_catalogue_serialize::Rgb&>(::transport_catalogue_serialize::_Rgb_default_instance_);
}
inline const ::transport_catalogue_serialize::Rgb& Color::rgb() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Color.rgb)
  return _internal_rgb();
}
inline ::transport_catalogue_serialize::Rgb* Color::unsafe_arena_release_rgb() {
  // @@protoc_insertion_point(field_unsafe_arena_release:transport_catalogue_serialize.Color.rgb)
  if (_internal_has_rgb()) {
    clear_has_color_variant();
    ::transport_catalogue_serialize::Rgb* temp = _impl_.color_variant_.rgb_;
    _impl_.color_variant_.rgb_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Color::unsafe_arena_set_allocated_rgb(::transport_catalogue_serialize::Rgb* rgb) {
  clear_color_variant();
  if (rgb) {
    set_has_rgb();
    _impl_.color_variant_.rgb_ = rgb;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_serialize.Color.rgb)
}
inline ::transport_catalogue_serialize::Rgb* Color::_internal_mutable_rgb() {
  if (!_internal_has_rgb()) {
    clear_color_variant();
    set_has_rgb();
    _impl_.color_variant_.rgb_ = CreateMaybeMessage< ::transport_catalogue_serialize::Rgb >(GetArenaForAllocation());
  }
  return _impl_.color_variant_.rgb_;
}
inline ::transport_catalogue_serialize::Rgb* Color::mutable_rgb() {
  ::transport_catalogue_serialize::Rgb* _msg = _internal_mutable_rgb();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_serialize.Color.rgb)
  return _msg;
}

// .transport_catalogue_serialize.Rgba rgba = 2;
inline bool Color::_internal_has_rgba() const {
  return color_variant_case() == kRgba;
}
inline bool Color::has_rgba() const {
  return _internal_has_rgba();
}
inline void Color::set_has_rgba() {
  _impl_._oneof_case_[0] = kRgba;
}
inline void Color::clear_rgba() {
  if (_internal_has_rgba()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.color_variant_.rgba_;
    }
    clear_has_color_variant();
  }
}
inline ::transport_catalogue_serialize::Rgba* Color::release_rgba() {
  // @@protoc_insertion_point(field_release:transport_catalogue_serialize.Color.rgba)
  if (_internal_has_rgba()) {
    clear_has_color_variant();
    ::transport_catalogue_serialize::Rgba* temp = _impl_.color_variant_.rgba_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.color_variant_.rgba_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::transport_catalogue_serialize::Rgba& Color::_internal_rgba() const {
  return _internal_has_rgba()
      ? *_impl_.color_variant_.rgba_
      : reinterpret_cast< ::transport_catalogue_serialize::Rgba&>(::transport_catalogue_serialize::_Rgba_default_instance_);
}
inline const ::transport_catalogue_serialize::Rgba& Color::rgba() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Color.rgba)
  return _internal_rgba();
}
inline ::transport_catalogue_serialize::Rgba* Color::unsafe_arena_release_rgba() {
  // @@protoc_insertion_point(field_unsafe_arena_release:transport_catalogue_serialize.Color.rgba)
  if (_internal_has_rgba()) {
    clear_has_color_variant();
    ::transport_catalogue_serialize::Rgba* temp = _impl_.color_variant_.rgba_;
    _impl_.color_variant_.rgba_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Color::unsafe_arena_set_allocated_rgba(::transport_catalogue_serialize::Rgba* rgba) {
  clear_color_variant();
  if (rgba) {
    set_has_rgba();
    _impl_.color_variant_.rgba_ = rgba;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_serialize.Color.rgba)
}
inline ::transport_catalogue_serialize::Rgba* Color::_internal_mutable_rgba() {
  if (!_internal_has_rgba()) {
    clear_color_variant();
    set_has_rgba();
    _impl_.color_variant_.rgba_ = CreateMaybeMessage< ::transport_catalogue_serialize::Rgba >(GetArenaForAllocation());
  }
  return _impl_.color_variant_.rgba_;
}
inline ::transport_catalogue_serialize::Rgba* Color::mutable_rgba() {
  ::transport_catalogue_serialize::Rgba* _msg = _internal_mutable_rgba();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_serialize.Color.rgba)
  return _msg;
}

// string color_str = 3;
inline bool Color::_internal_has_color_str() const {
  return color_variant_case() == kColorStr;
}
inline bool Color::has_color_str() const {
  return _internal_has_color_str();
}
inline void Color::set_has_color_str() {
  _impl_._oneof_case_[0] = kColorStr;
}
inline void Color::clear_color_str() {
  if (_internal_has_color_str()) {
    _impl_.color_variant_.color_str_.Destroy();
    clear_has_color_variant();
  }
}
inline const std::string& Color::color_str() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.Color.color_str)
  return _internal_color_str();
}
template <typename ArgT0, typename... ArgT>
inline void Color::set_color_str(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_color_str()) {
    clear_color_variant();
    set_has_color_str();
    _impl_.color_variant_.color_str_.InitDefault();
  }
  _impl_.color_variant_.color_str_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.Color.color_str)
}
inline std::string* Color::mutable_color_str() {
  std::string* _s = _internal_mutable_color_str();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_serialize.Color.color_str)
  return _s;
}
inline const std::string& Color::_internal_color_str() const {
  if (_internal_has_color_str()) {
    return _impl_.color_variant_.color_str_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Color::_internal_set_color_str(const std::string& value) {
  if (!_internal_has_color_str()) {
    clear_color_variant();
    set_has_color_str();
    _impl_.color_variant_.color_str_.InitDefault();
  }
  _impl_.color_variant_.color_str_.Set(value, GetArenaForAllocation());
}
inline std::string* Color::_internal_mutable_color_str() {
  if (!_internal_has_color_str()) {
    clear_color_variant();
    set_has_color_str();
    _impl_.color_variant_.color_str_.InitDefault();
  }
  return _impl_.color_variant_.color_str_.Mutable(      GetArenaForAllocation());
}
inline std::string* Color::release_color_str() {
  // @@protoc_insertion_point(field_release:transport_catalogue_serialize.Color.color_str)
  if (_internal_has_color_str()) {
    clear_has_color_variant();
    return _impl_.color_variant_.color_str_.Release();
  } else {
    return nullptr;
  }
}
inline void Color::set_allocated_color_str(std::string* color_str) {
  if (has_color_variant()) {
    clear_color_variant();
  }
  if (color_str != nullptr) {
    set_has_color_str();
    _impl_.color_variant_.color_str_.InitAllocated(color_str, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_serialize.Color.color_str)
}

inline bool Color::has_color_variant() const {
  return color_variant_case() != COLOR_VARIANT_NOT_SET;
}
inline void Color::clear_has_color_variant() {
  _impl_._oneof_case_[0] = COLOR_VARIANT_NOT_SET;
}
inline Color::ColorVariantCase Color::color_variant_case() const {
  return Color::ColorVariantCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace transport_catalogue_serialize

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_svg_2eproto
