// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_router.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transport_5frouter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transport_5frouter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "graph.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transport_5frouter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transport_5frouter_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transport_5frouter_2eproto;
namespace transport_catalogue_serialize {
class RoutingSettings;
struct RoutingSettingsDefaultTypeInternal;
extern RoutingSettingsDefaultTypeInternal _RoutingSettings_default_instance_;
class TransportRouter;
struct TransportRouterDefaultTypeInternal;
extern TransportRouterDefaultTypeInternal _TransportRouter_default_instance_;
}  // namespace transport_catalogue_serialize
PROTOBUF_NAMESPACE_OPEN
template<> ::transport_catalogue_serialize::RoutingSettings* Arena::CreateMaybeMessage<::transport_catalogue_serialize::RoutingSettings>(Arena*);
template<> ::transport_catalogue_serialize::TransportRouter* Arena::CreateMaybeMessage<::transport_catalogue_serialize::TransportRouter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace transport_catalogue_serialize {

// ===================================================================

class RoutingSettings final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_serialize.RoutingSettings) */ {
 public:
  inline RoutingSettings() : RoutingSettings(nullptr) {}
  ~RoutingSettings() override;
  explicit PROTOBUF_CONSTEXPR RoutingSettings(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoutingSettings(const RoutingSettings& from);
  RoutingSettings(RoutingSettings&& from) noexcept
    : RoutingSettings() {
    *this = ::std::move(from);
  }

  inline RoutingSettings& operator=(const RoutingSettings& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoutingSettings& operator=(RoutingSettings&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoutingSettings& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoutingSettings* internal_default_instance() {
    return reinterpret_cast<const RoutingSettings*>(
               &_RoutingSettings_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoutingSettings& a, RoutingSettings& b) {
    a.Swap(&b);
  }
  inline void Swap(RoutingSettings* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoutingSettings* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoutingSettings* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoutingSettings>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoutingSettings& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoutingSettings& from) {
    RoutingSettings::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoutingSettings* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_serialize.RoutingSettings";
  }
  protected:
  explicit RoutingSettings(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBusVelocityKmhFieldNumber = 2,
    kBusWaitTimeMinFieldNumber = 1,
  };
  // double bus_velocity_kmh = 2;
  void clear_bus_velocity_kmh();
  double bus_velocity_kmh() const;
  void set_bus_velocity_kmh(double value);
  private:
  double _internal_bus_velocity_kmh() const;
  void _internal_set_bus_velocity_kmh(double value);
  public:

  // uint32 bus_wait_time_min = 1;
  void clear_bus_wait_time_min();
  uint32_t bus_wait_time_min() const;
  void set_bus_wait_time_min(uint32_t value);
  private:
  uint32_t _internal_bus_wait_time_min() const;
  void _internal_set_bus_wait_time_min(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalogue_serialize.RoutingSettings)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double bus_velocity_kmh_;
    uint32_t bus_wait_time_min_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transport_5frouter_2eproto;
};
// -------------------------------------------------------------------

class TransportRouter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_serialize.TransportRouter) */ {
 public:
  inline TransportRouter() : TransportRouter(nullptr) {}
  ~TransportRouter() override;
  explicit PROTOBUF_CONSTEXPR TransportRouter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransportRouter(const TransportRouter& from);
  TransportRouter(TransportRouter&& from) noexcept
    : TransportRouter() {
    *this = ::std::move(from);
  }

  inline TransportRouter& operator=(const TransportRouter& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransportRouter& operator=(TransportRouter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransportRouter& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransportRouter* internal_default_instance() {
    return reinterpret_cast<const TransportRouter*>(
               &_TransportRouter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TransportRouter& a, TransportRouter& b) {
    a.Swap(&b);
  }
  inline void Swap(TransportRouter* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransportRouter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransportRouter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransportRouter>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransportRouter& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TransportRouter& from) {
    TransportRouter::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransportRouter* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_serialize.TransportRouter";
  }
  protected:
  explicit TransportRouter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBusRoutesFieldNumber = 2,
    kSettingsFieldNumber = 1,
  };
  // repeated .transport_catalogue_serialize.BusRoute bus_routes = 2;
  int bus_routes_size() const;
  private:
  int _internal_bus_routes_size() const;
  public:
  void clear_bus_routes();
  ::transport_catalogue_serialize::BusRoute* mutable_bus_routes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_serialize::BusRoute >*
      mutable_bus_routes();
  private:
  const ::transport_catalogue_serialize::BusRoute& _internal_bus_routes(int index) const;
  ::transport_catalogue_serialize::BusRoute* _internal_add_bus_routes();
  public:
  const ::transport_catalogue_serialize::BusRoute& bus_routes(int index) const;
  ::transport_catalogue_serialize::BusRoute* add_bus_routes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_serialize::BusRoute >&
      bus_routes() const;

  // .transport_catalogue_serialize.RoutingSettings settings = 1;
  bool has_settings() const;
  private:
  bool _internal_has_settings() const;
  public:
  void clear_settings();
  const ::transport_catalogue_serialize::RoutingSettings& settings() const;
  PROTOBUF_NODISCARD ::transport_catalogue_serialize::RoutingSettings* release_settings();
  ::transport_catalogue_serialize::RoutingSettings* mutable_settings();
  void set_allocated_settings(::transport_catalogue_serialize::RoutingSettings* settings);
  private:
  const ::transport_catalogue_serialize::RoutingSettings& _internal_settings() const;
  ::transport_catalogue_serialize::RoutingSettings* _internal_mutable_settings();
  public:
  void unsafe_arena_set_allocated_settings(
      ::transport_catalogue_serialize::RoutingSettings* settings);
  ::transport_catalogue_serialize::RoutingSettings* unsafe_arena_release_settings();

  // @@protoc_insertion_point(class_scope:transport_catalogue_serialize.TransportRouter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_serialize::BusRoute > bus_routes_;
    ::transport_catalogue_serialize::RoutingSettings* settings_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transport_5frouter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoutingSettings

// uint32 bus_wait_time_min = 1;
inline void RoutingSettings::clear_bus_wait_time_min() {
  _impl_.bus_wait_time_min_ = 0u;
}
inline uint32_t RoutingSettings::_internal_bus_wait_time_min() const {
  return _impl_.bus_wait_time_min_;
}
inline uint32_t RoutingSettings::bus_wait_time_min() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.RoutingSettings.bus_wait_time_min)
  return _internal_bus_wait_time_min();
}
inline void RoutingSettings::_internal_set_bus_wait_time_min(uint32_t value) {
  
  _impl_.bus_wait_time_min_ = value;
}
inline void RoutingSettings::set_bus_wait_time_min(uint32_t value) {
  _internal_set_bus_wait_time_min(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.RoutingSettings.bus_wait_time_min)
}

// double bus_velocity_kmh = 2;
inline void RoutingSettings::clear_bus_velocity_kmh() {
  _impl_.bus_velocity_kmh_ = 0;
}
inline double RoutingSettings::_internal_bus_velocity_kmh() const {
  return _impl_.bus_velocity_kmh_;
}
inline double RoutingSettings::bus_velocity_kmh() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.RoutingSettings.bus_velocity_kmh)
  return _internal_bus_velocity_kmh();
}
inline void RoutingSettings::_internal_set_bus_velocity_kmh(double value) {
  
  _impl_.bus_velocity_kmh_ = value;
}
inline void RoutingSettings::set_bus_velocity_kmh(double value) {
  _internal_set_bus_velocity_kmh(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_serialize.RoutingSettings.bus_velocity_kmh)
}

// -------------------------------------------------------------------

// TransportRouter

// .transport_catalogue_serialize.RoutingSettings settings = 1;
inline bool TransportRouter::_internal_has_settings() const {
  return this != internal_default_instance() && _impl_.settings_ != nullptr;
}
inline bool TransportRouter::has_settings() const {
  return _internal_has_settings();
}
inline void TransportRouter::clear_settings() {
  if (GetArenaForAllocation() == nullptr && _impl_.settings_ != nullptr) {
    delete _impl_.settings_;
  }
  _impl_.settings_ = nullptr;
}
inline const ::transport_catalogue_serialize::RoutingSettings& TransportRouter::_internal_settings() const {
  const ::transport_catalogue_serialize::RoutingSettings* p = _impl_.settings_;
  return p != nullptr ? *p : reinterpret_cast<const ::transport_catalogue_serialize::RoutingSettings&>(
      ::transport_catalogue_serialize::_RoutingSettings_default_instance_);
}
inline const ::transport_catalogue_serialize::RoutingSettings& TransportRouter::settings() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.TransportRouter.settings)
  return _internal_settings();
}
inline void TransportRouter::unsafe_arena_set_allocated_settings(
    ::transport_catalogue_serialize::RoutingSettings* settings) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.settings_);
  }
  _impl_.settings_ = settings;
  if (settings) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_serialize.TransportRouter.settings)
}
inline ::transport_catalogue_serialize::RoutingSettings* TransportRouter::release_settings() {
  
  ::transport_catalogue_serialize::RoutingSettings* temp = _impl_.settings_;
  _impl_.settings_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::transport_catalogue_serialize::RoutingSettings* TransportRouter::unsafe_arena_release_settings() {
  // @@protoc_insertion_point(field_release:transport_catalogue_serialize.TransportRouter.settings)
  
  ::transport_catalogue_serialize::RoutingSettings* temp = _impl_.settings_;
  _impl_.settings_ = nullptr;
  return temp;
}
inline ::transport_catalogue_serialize::RoutingSettings* TransportRouter::_internal_mutable_settings() {
  
  if (_impl_.settings_ == nullptr) {
    auto* p = CreateMaybeMessage<::transport_catalogue_serialize::RoutingSettings>(GetArenaForAllocation());
    _impl_.settings_ = p;
  }
  return _impl_.settings_;
}
inline ::transport_catalogue_serialize::RoutingSettings* TransportRouter::mutable_settings() {
  ::transport_catalogue_serialize::RoutingSettings* _msg = _internal_mutable_settings();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_serialize.TransportRouter.settings)
  return _msg;
}
inline void TransportRouter::set_allocated_settings(::transport_catalogue_serialize::RoutingSettings* settings) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.settings_;
  }
  if (settings) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(settings);
    if (message_arena != submessage_arena) {
      settings = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, settings, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.settings_ = settings;
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_serialize.TransportRouter.settings)
}

// repeated .transport_catalogue_serialize.BusRoute bus_routes = 2;
inline int TransportRouter::_internal_bus_routes_size() const {
  return _impl_.bus_routes_.size();
}
inline int TransportRouter::bus_routes_size() const {
  return _internal_bus_routes_size();
}
inline ::transport_catalogue_serialize::BusRoute* TransportRouter::mutable_bus_routes(int index) {
  // @@protoc_insertion_point(field_mutable:transport_catalogue_serialize.TransportRouter.bus_routes)
  return _impl_.bus_routes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_serialize::BusRoute >*
TransportRouter::mutable_bus_routes() {
  // @@protoc_insertion_point(field_mutable_list:transport_catalogue_serialize.TransportRouter.bus_routes)
  return &_impl_.bus_routes_;
}
inline const ::transport_catalogue_serialize::BusRoute& TransportRouter::_internal_bus_routes(int index) const {
  return _impl_.bus_routes_.Get(index);
}
inline const ::transport_catalogue_serialize::BusRoute& TransportRouter::bus_routes(int index) const {
  // @@protoc_insertion_point(field_get:transport_catalogue_serialize.TransportRouter.bus_routes)
  return _internal_bus_routes(index);
}
inline ::transport_catalogue_serialize::BusRoute* TransportRouter::_internal_add_bus_routes() {
  return _impl_.bus_routes_.Add();
}
inline ::transport_catalogue_serialize::BusRoute* TransportRouter::add_bus_routes() {
  ::transport_catalogue_serialize::BusRoute* _add = _internal_add_bus_routes();
  // @@protoc_insertion_point(field_add:transport_catalogue_serialize.TransportRouter.bus_routes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_serialize::BusRoute >&
TransportRouter::bus_routes() const {
  // @@protoc_insertion_point(field_list:transport_catalogue_serialize.TransportRouter.bus_routes)
  return _impl_.bus_routes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace transport_catalogue_serialize

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transport_5frouter_2eproto
